# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:13
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${DB_PORT:-5432}:5432'

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT:-8080}:8080'
